import express from 'express';
import Anthropic from '@anthropic-ai/sdk';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
dotenv.config({ path: path.join(__dirname, '../.env') });

const router = express.Router();

const client = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY || 'dummy_key_if_not_set',
});

const SYSTEM_PROMPTS = {
  en: `You are an official AI assistant for the Indian Police complaint portal. 
Respond only in the language the user writes in (Telugu, Hindi, or English).
Your job is to help citizens file police complaints accurately and compassionately.
Ask one question at a time. Extract key complaint details and return them as JSON 
in a hidden block at the end of your message like:
<!--FORM_DATA:{"complaintType":"...","incidentDate":"...","incidentTime":"...","incidentLocation":"...","description":"...","suspectDetails":"...","witnessInfo":"..."}-->`,

  hi: `आप भारतीय पुलिस शिकायत पोर्टल के लिए एक आधिकारिक AI सहायक हैं।
उपयोगकर्ता जिस भाषा में लिखता है (तेलुगु, हिंदी या अंग्रेजी), उसी भाषा में उत्तर दें।
आपका काम नागरिकों को पुलिस शिकायत सटीक और सहानुभूतिपूर्ण तरीके से दर्ज करने में मदद करना है।
एक समय में एक प्रश्न पूछें। मुख्य शिकायत विवरण निकालें और उन्हें अपने संदेश के अंत में एक छिपे हुए ब्लॉक में JSON के रूप में लौटाएं:
<!--FORM_DATA:{"complaintType":"...","incidentDate":"...","incidentTime":"...","incidentLocation":"...","description":"...","suspectDetails":"...","witnessInfo":"..."}-->`,

  te: `మీరు భారతీయ పోలీస్ ఫిర్యాదు పోర్టల్ కోసం అధికారిక AI సహాయకుడు.
వినియోగదారు ఏ భాషలో (తెలుగు, హిందీ లేదా ఇంగ్లీష్) రాస్తారో అదే భాషలో సమాధానం ఇవ్వండి.
ఖచ్చితంగా మరియు సానుభూతితో పోలీస్ ఫిర్యాదులను నమోదు చేయడంలో పౌరులకు సహాయపడటం మీ పని.
ఒకేసారి ఒక ప్రశ్న మాత్రమే అడగండి. ముఖ్యమైన ఫిర్యాదు వివరాలను సేకరించి, మీ సందేశం చివరన దాచిన బ్లాక్‌లో JSON రూపంలో దాన్ని తిరిగి ఇవ్వండి:
<!--FORM_DATA:{"complaintType":"...","incidentDate":"...","incidentTime":"...","incidentLocation":"...","description":"...","suspectDetails":"...","witnessInfo":"..."}-->`
};

router.post('/', async (req, res) => {
  const { messages, language = 'en' } = req.body;
  
  if (!process.env.ANTHROPIC_API_KEY) {
      console.warn("WARNING: No ANTHROPIC_API_KEY set. Returning mock response.");
      return res.json({ 
          content: "I am functioning in offline mock mode because no Anthropic API key was found in `server/.env`. I've automatically filled out your form with testing data right now so you can see how the extraction architecture works!\n\n<!--FORM_DATA:{\"fullName\":\"Citizen Demo\",\"mobileNumber\":\"9876543210\",\"complaintType\":\"Theft\",\"incidentDate\":\"2024-03-22\",\"incidentTime\":\"14:30\",\"incidentLocation\":\"Hyderabad Central Station\",\"description\":\"This is a mock description generated by the offline system. I am testing the AI extraction capabilities without an API key.\"}-->" 
      });
  }

  try {
    const response = await client.messages.create({
      model: 'claude-3-5-sonnet-20240620', // Updating to available sonnet version
      max_tokens: 1024,
      system: SYSTEM_PROMPTS[language],
      messages
    });
    
    // We expect the first element of 'content' to be a text block
    res.json({ content: response.content[0]?.text || '' });
  } catch (error) {
    console.error('Anthropic API Error:', error);
    res.status(500).json({ error: 'Failed to communicate with AI' });
  }
});

export default router;
