import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generateComplaintPDF = (data, refNumber) => {
  const doc = new jsPDF();
  
  // Set fonts and styles
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("CITIZEN POLICE PORTAL", 105, 20, { align: "center" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(14);
  doc.text("OFFICIAL COMPLAINT ACKNOWLEDGEMENT", 105, 30, { align: "center" });

  // Watermark
  doc.setTextColor(230, 230, 235);
  doc.setFontSize(60);
  doc.text("COMPLAINT COPY", 105, 150, { align: "center", angle: 45 });
  
  // Reset text color
  doc.setTextColor(0, 0, 0);
  
  doc.setFontSize(12);
  doc.text(`Reference Number: ${refNumber}`, 14, 45);
  doc.text(`Date Issued: ${new Date().toLocaleDateString()}`, 140, 45);

  const tableData = [
    ['Full Name', data.fullName],
    ['Mobile Number', data.mobileNumber],
    ['Email', data.email || 'N/A'],
    ['Address', `${data.address}, ${data.district}, ${data.state}`],
    ['Complaint Type', data.complaintType],
    ['Incident Date & Time', `${data.incidentDate} at ${data.incidentTime}`],
    ['Incident Location', data.incidentLocation],
  ];

  autoTable(doc, {
    startY: 55,
    head: [['Field', 'Details']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [217, 119, 6] }, // amber-600 to match tech theme
    styles: { fontSize: 11, cellPadding: 4 },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 50 },
      1: { cellWidth: 130 }
    }
  });

  const currentY = doc.lastAutoTable.finalY + 10;
  
  doc.setFont("helvetica", "bold");
  doc.text("Detailed Description:", 14, currentY);
  
  doc.setFont("helvetica", "normal");
  const splitDescription = doc.splitTextToSize(data.description, 180);
  doc.text(splitDescription, 14, currentY + 7);

  const footerY = 280;
  doc.setFontSize(10);
  doc.text("Generated by Citizen Police Portal | Helps lines: 100 (Police), 1091 (Women), 1930 (Cyber)", 105, footerY, { align: "center" });

  doc.save(`Complaint_${refNumber}.pdf`);
};
